"""auto-vote

Revision ID: 3b1becf26f4c
Revises: 0f328bfd2a74
Create Date: 2021-12-04 19:47:45.057259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b1becf26f4c'
down_revision = '0f328bfd2a74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
